In [2]:
import sys, os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, PReLU
from keras.layers import Conv2D, MaxPooling2D, BatchNormalization, AveragePooling2D
from keras.losses import categorical_crossentropy
from keras.optimizers import SGD, adadelta
from keras.regularizers import l2
from keras.callbacks import ReduceLROnPlateau, TensorBoard, EarlyStopping, ModelCheckpoint
from keras.models import load_model
from keras.utils import to_categorical
from keras.preprocessing import image

In [3]:
model = Sequential()
model.add(Conv2D(64,(5,5),input_shape =(64,64,1),padding='same'))
model.add(PReLU(init='zero',weights=None))
model.add(BatchNormalization())
model.add(MaxPooling2D((5, 5),strides=(2,2)))  ## 24 x 24

model.add(Conv2D(64, (3, 3), strides=1, padding='same'))
model.add(PReLU(init='zero', weights=None))
model.add(BatchNormalization())
model.add(Conv2D(64, (3, 3), strides=1, padding='same'))
model.add(PReLU(init='zero', weights=None))
model.add(AveragePooling2D((3,3),strides=(2,2)))

model.add(Conv2D(128, (3, 3), strides=1, padding='same'))
model.add(PReLU(init='zero', weights=None))
model.add(BatchNormalization())
model.add(Conv2D(128, (3, 3), strides=1, padding='same'))
model.add(PReLU(init='zero', weights=None))
model.add(BatchNormalization())
model.add(AveragePooling2D((3,3),strides=(2,2)))

model.add(Flatten())
model.add(Dense(1024))
model.add(PReLU(init='zero', weights=None))
model.add(Dropout(0.2))
model.add(Dense(1024))
model.add(PReLU(init='zero', weights=None))
model.add(Dropout(0.2))
model.add(Dense(5, activation='softmax'))

Instructions for updating:
Colocations handled automatically by placer.


C:\Users\jaehee\Anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `PReLU` call to the Keras 2 API: `PReLU(weights=None, alpha_initializer="zero")`
  This is separate from the ipykernel package so we can avoid doing imports until
C:\Users\jaehee\Anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:8: UserWarning: Update your `PReLU` call to the Keras 2 API: `PReLU(weights=None, alpha_initializer="zero")`
  
C:\Users\jaehee\Anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:11: UserWarning: Update your `PReLU` call to the Keras 2 API: `PReLU(weights=None, alpha_initializer="zero")`
  # This is added back by InteractiveShellApp.init_path()
C:\Users\jaehee\Anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:15: UserWarning: Update your `PReLU` call to the Keras 2 API: `PReLU(weights=None, alpha_initializer="zero")`
  from ipykernel import kernelapp as app
C:\Users\jaehee\Anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.p

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.


C:\Users\jaehee\Anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:24: UserWarning: Update your `PReLU` call to the Keras 2 API: `PReLU(weights=None, alpha_initializer="zero")`
C:\Users\jaehee\Anaconda3\envs\venv\lib\site-packages\ipykernel_launcher.py:27: UserWarning: Update your `PReLU` call to the Keras 2 API: `PReLU(weights=None, alpha_initializer="zero")`


In [4]:
from IPython.display import SVG
from keras.utils.vis_utils import model_to_dot

%matplotlib inline

SVG(model_to_dot(model, show_shapes=True).create(prog='dot',format='svg'))

ImportError: Failed to import `pydot`. Please install `pydot`. For example with `pip install pydot`.

In [5]:
from keras.preprocessing.image import ImageDataGenerator
train_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(
        './data/FER2013Train/',
        target_size=(64, 64),
        color_mode="grayscale",
        batch_size=24,
        class_mode='categorical')

test_datagen = ImageDataGenerator(rescale=1./255)

test_generator = test_datagen.flow_from_directory(
        './data/FER2013Test/',
        target_size=(64, 64),
        color_mode="grayscale",
        batch_size=5,
        class_mode='categorical')

Found 40000 images belonging to 5 classes.
Found 8654 images belonging to 5 classes.


In [6]:
model.compile(loss='categorical_crossentropy'
, optimizer=adadelta(lr=0.03, rho=0.95,epsilon=1e-08)
, metrics=['accuracy']
)
 
model.fit_generator(train_generator, steps_per_epoch=1666, epochs=30,
                    validation_data=test_generator,validation_steps=1730)

Epoch 1/30
1666/1666 [==============================] - 3056s 2s/step - loss: 1.0204 - acc: 0.6008 - val_loss: 1.0329 - val_acc: 0.6156
Epoch 2/30
1666/1666 [==============================] - 2695s 2s/step - loss: 0.8568 - acc: 0.6707 - val_loss: 0.9547 - val_acc: 0.6348
Epoch 3/30
1666/1666 [==============================] - 2656s 2s/step - loss: 0.7609 - acc: 0.7107 - val_loss: 0.9583 - val_acc: 0.6663
Epoch 4/30
1666/1666 [==============================] - 3476s 2s/step - loss: 0.6833 - acc: 0.7434 - val_loss: 0.8956 - val_acc: 0.6800
Epoch 5/30
1666/1666 [==============================] - 5091s 3s/step - loss: 0.6251 - acc: 0.7657 - val_loss: 0.8322 - val_acc: 0.6952
Epoch 6/30
1666/1666 [==============================] - 3411s 2s/step - loss: 0.5739 - acc: 0.7863 - val_loss: 1.1177 - val_acc: 0.6612
Epoch 7/30
1666/1666 [==============================] - 4439s 3s/step - loss: 0.5300 - acc: 0.8067 - val_loss: 0.8309 - val_acc: 0.6906
Epoch 8/30
1666/1666 [==========================

In [7]:
print("-- Evaluate --")
scores = model.evaluate_generator(test_generator, steps=1134)
print("%s: %.2f%%" %(model.metrics_names[1], scores[1]*100))

print(" -------------------------------------------------------------------------")
print("-- Predict --")
output = model.predict_generator(test_generator, steps=5)
np.set_printoptions(formatter={'float': lambda x: "{0:0.3f}".format(x)})
print(test_generator.class_indices)
print(output)


-- Evaluate --
acc: 75.19%
 -------------------------------------------------------------------------
-- Predict --
{'Angry': 0, 'Happy': 1, 'Neutral': 2, 'Sad': 3, 'Surprise': 4}
[[0.000 0.000 0.000 0.000 1.000]
 [0.001 0.008 0.937 0.045 0.009]
 [0.000 0.166 0.821 0.011 0.002]
 [0.779 0.034 0.004 0.080 0.103]
 [0.974 0.000 0.000 0.014 0.012]
 [0.000 0.033 0.175 0.004 0.787]
 [0.999 0.000 0.000 0.000 0.001]
 [0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 1.000 0.000 0.000]
 [0.000 0.000 0.000 0.000 1.000]
 [0.991 0.001 0.000 0.006 0.002]
 [1.000 0.000 0.000 0.000 0.000]
 [0.000 0.003 0.001 0.996 0.000]
 [0.994 0.000 0.000 0.002 0.005]
 [0.001 0.001 0.125 0.000 0.874]
 [0.166 0.550 0.147 0.001 0.135]
 [0.896 0.000 0.100 0.004 0.000]
 [0.000 0.745 0.043 0.212 0.000]
 [0.286 0.000 0.000 0.000 0.714]
 [0.990 0.000 0.000 0.000 0.010]
 [0.006 0.000 0.000 0.000 0.994]
 [0.000 0.000 0.000 0.000 1.000]
 [0.000 0.000 1.000 0.000 0.000]
 [0.000 0.002 0.002 0.994 0.002]
 [0.000 0.001 0.000 0.998 0.

In [8]:
from keras.models import load_model

model.save('model_emotion_plelu_0.03_30_gray_new.h5')